language: python

matrix:
  include:
    - python: '3.6'
      env: TOXENV=py36-coverage
    - python: '3.6'
      env: TOXENV=pylama

install:
  - pip install tox coveralls

script:
  - tox

sudo: required

after_success:
  - coveralls
